spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: vini123
    driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          # Força o dialeto explicitamente caso o Hibernate não consiga autodetectar na inicialização
          dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: TRACE
